### ISSUE TITLE
Explore removing `src` and just having `menelaus`

### ISSUE THREAD

**Issue by Anmol-Srivastava** [mitre/menelaus#105]
It would be nice to mimic most libraries that just have a `library_name` source folder, and would also help embrace the pattern of test directory structure mimicking code structure.

**Comment by Anmol-Srivastava** [comment]
I also think it makes sense to just call it `detector.py`

**Comment by tms-bananaquit** [comment]
@Anmol-Srivastava  Yeah, agree it looks weird. Should fix it at some point.
