### ISSUE TITLE
Debug issue where kdqpartitioner makes leaves with large counts

### ISSUE THREAD

**Issue by macandleighs** [mitre/menelaus#20]
If you run the detector(partitioner) with this data, we somehow get a leaf of size ~8000 despite having a maximum leaf count of 100. This may have something to do with the uniqueness criterion, but removing it didn't change the behavior.

**Comment by tms-bananaquit** [comment]
The original files were lost in the transition to gitlab, and I think it's likely this has more to do with not-handling categorical data than any specific problem with the code.

When we tackle supporting categorical data with kdq-tree, I expect it'll crop up again, at which point we can address it.
