### ISSUE TITLE
Look into alternative partitioners for kdq-Tree

### ISSUE THREAD

**Issue by tms-bananaquit** [mitre/menelaus#23]
[Quad-tree](http://proceedings.mlr.press/v80/boracchi18a/boracchi18a.pdf) is a similar partitioning algorithm. Can we set up that detector/partitioner pair s.t. arbitrary divergence metrics over tree-based partitions can be (bootstrapped) and used?

**Comment by Anmol-Srivastava** [comment]
Closing as #106 seems to provide an alternative partitioner and next steps
