### ISSUE TITLE
EDDM: store the n-ago of when drift/warning began (L120)

### ISSUE THREAD

**Issue by macandleighs** [mitre/menelaus#29]
Author Owner

As in self.buffer_size of STEPD

**Comment by tms-bananaquit** [comment]
This is effectively already stored as `self.retraining_recs`, the difference being that if the detector "hammers" between `warning` and `None` we lose that information.

I don't think this is reasonably solve-able with the detector itself, but one might fiddle with the outer loop to define a more "permissive" drift region.
