### ISSUE TITLE
Split up the linting and formatting workflows

### ISSUE THREAD

**Issue by tms-bananaquit** [mitre/menelaus#4]
- Split off the linting action (flake8)
- Split off the formatting actions
   - include `black`

**Comment by tms-bananaquit** [comment]
We might shave off a couple seconds by specifying a new option in `setup.cfg[extras_require]` that only installs the linters to run them.

**Comment by Anmol-Srivastava** [comment]
The `black` check works as discussed now, just need to actually run black to satisfy it and pass the job, and maybe update the README.
