### ISSUE TITLE
Make streaming and batch abstract classes

### ISSUE THREAD

**Issue by tms-bananaquit** [mitre/menelaus#46]
kdq-tree has a lot of weirdness due to handling both streaming and batch, e.g. in the validation: right now, the dimensions of new numpy arrays aren't checked. We could probably add checks for the length of `self.input_cols` vs the shape of a numpy array. This still doesn't seem ideal, but it's definitely break-able as it is.

Rather than continuing to fool with the complications introduced by the detector taking both streaming and batch input, we should probably have parallel classes that have dependency on the same partitioner/similar. This seems like a better structure going forward, as we add more detectors that can do both. The further we get into implementing validation and similar, the more troublesome these problems are.

**Comment by Anmol-Srivastava** [comment]
A little tangent regarding method resolution order (MRO) with the multiple inheritance scheme. The following is how I've designed the new scheme.

```python
class A():
    def __init__(self, a):
        self.a = a 

class B():
    def __init__(self, b):
        self.b = b

class C(A, B):
    def __init__(self, a, b, c):
        A.__init__(self, a)
        B.__init__(self, b)
        self.c = c 

if __name__ == '__main__':
    o = C(a=1, b=2, c=3)
```

I've based this off of [Nathaniel Jones' answer, in the "Source code accessible: correct use of 'old style'" portion, within this StackOverflow question](https://stackoverflow.com/questions/9575409/calling-parent-class-init-with-multiple-inheritance-whats-the-right-way).

However it may still be determined that our system is or is not 'designed for multiple inheritance', and that some other structure e.g. mixin classes or the like may be more applicable.
