### ISSUE TITLE
Split off and configure the testing pipeline

### ISSUE THREAD

**Issue by tms-bananaquit** [mitre/menelaus#5]
- The current workflow runs coverage tests. Split it into a separate .yml.
- Coverage % badges seem to be nonstandard for GitHub. At a minimum, figure out a way to pass/fail coverage based on whether 99% or higher is achieved.

**Comment by tms-bananaquit** [comment]
Note that the `test` option was added in `setup.cfg`, so `pip install -e .[test]` should specifically avoid pulling in extraneous sphinx libraries, etc.

**Comment by Anmol-Srivastava** [comment]
I think test + cov should stay in one workflow, and issues e.g. #9 may recommend cleaning out the unrelated lint/formatting steps into other workflows. Otherwise this issue is PR-ready after adding the `--fail-under=99` flag to `coverage report -m`

**Comment by tms-bananaquit** [comment]
Yeah, I think when I made these issues I just made "one issue per workflow we need," because current state is that linting/formatting/coverage all run in the same workflow. (#4). So doing coverage/test in the same makes sense, and linting/formatting either as one or two, not a huge deal either way.

I think doing one PR for this, #4, and #7 works fine.
