### ISSUE TITLE
Follow multi-inheritance pattern for all applicable detectors

### ISSUE THREAD

**Issue by Anmol-Srivastava** [mitre/menelaus#61]
### Task

After #46, all remaining detectors outside of `KdqTree` will need to be updated, to now use the `StreamingDetector` and `BatchDetector` ABCs if they are meant to service both options. Such detectors will (likely) also need to implement their own parent algorithm class, e.g. `KdqTreeDetector` as part of the multi-inheritance pattern.

### Impact

This will significantly progress the broad refactor of the drift detectors' object design. See also #15

**Comment by Anmol-Srivastava** [comment]
To complete the refactor, it is first necessary to determine:
- which detectors need to be refactored into streaming detector child classes
- which need to be made into batch detector child classes
- which need both

_**Note that a detector being exclusively batch/streaming should not prevent us from isolating as much 'other' logic into the parent algorithm class as possible**_. Currently:

Streaming only:
- `CUSUM`
- `PageHinkely`
Batch only:
- ??? TBD
Both:
- ??? TBD

**Comment by Anmol-Srivastava** [comment]
Optionally, multiple branches can be made to develop on each of the involved detectors and linked into one PR for this issue.

**Comment by tms-bananaquit** [comment]
Checking these off as I go -- not necessarily setting them up with maximum possible refactoring into a parent class, but making sure that they each inherit the proper ABC.

**Comment by Anmol-Srivastava** [comment]
@tms-bananaquit sounds good; later we can push the parent class concept if we know that certain of these detectors may need to be both streaming/batch

**Comment by tms-bananaquit** [comment]
@Anmol-Srivastava Going to go ahead and close unless there's objection. #70 can finish deprecating `DriftDetector` entirely.
