### ISSUE TITLE
Investigate curried pipeline for potential ensemble detectors

### ISSUE THREAD

**Issue by Anmol-Srivastava** [mitre/menelaus#77]
### Overview

As seen in #15, we want to standardize function signatures as best we can so that a future ensemble detector may iterative over several different algorithms and be able to dump any possible arguments in without error. Not all detectors will use these arguments:

```python
for det in detector:
    det.set_reference(X, y_true, y_pred)
    det.update(X, y_true, y_pred)
```

This is tricky because sometimes the targets are positional values and `X=None` by default, and sometimes the other way around (e.g. concept vs drift detectors). More importantly, **_the idea of a standardized `set_reference` doesn't even apply to streaming detectors._** This creates an issue for a future ensemble, where even batch detectors have different 'waiting' logic while reference data is set:

```python
for det in detector:
    if isinstance(det, BatchDetector) or det.input_type == 'batch':
        # determine wait period for this algorithm
        # set reference as needed
    det.update()
```

Rather than further standardizing names of wait attributes, and other attributes between streaming/batch detectors, we may want to explore a pipeline flow that is specified prior to iteration over the data. A pipeline example from [the LEAP library](https://github.com/AureumChaos/LEAP) shows an individual in a population being _**curried**_ from one operator function to the next. Each operator modifies and returns the individual, creating a pipeline.

```python
pipeline=[
     # Select parents via tournament_selection selection
     ops.tournament_selection,
     ops.clone,  # Copy them (just to be safe)
     # Basic mutation with a 1/L mutation rate
     mutate_bitflip(expected_num_mutations=1),
     # Crossover with a 40% chance of swapping each gene
     ops.uniform_crossover(p_swap=0.4),
     ops.evaluate,  # Evaluate fitness
     # Collect offspring into a new population
     ops.pool(size=pop_size)
])
```

It's worth thinking about applying this to ensemble classes, or to the individual detectors within. Something like:

```python
# on detectors
pipeline_for_kdqtree = [
    function_that_sets_up_any_initial_waiting(),
    function_that_updates(),
]

# on ensembles
pipeline_for_ensemble_object = [
    function_for_setting_up_one_or_more_detectors(),
    function_that_updates_one_or_more_detectors()
]
```

**Comment by Anmol-Srivastava** [comment]
The above is a very half-baked idea. But the more we can flesh out a pipeline structure, the less dependent we may be on having to standardize function signatures, waiting attributes, and more @tms-bananaquit

**Comment by tms-bananaquit** [comment]
Copying over a summary of a conversation with @Anmol-Srivastava:

If I wanted to implement a simple ensemble that does majority voting on drift_state, would it look sort of like this?

```
def update(ensemble, detectors):
   [det.update for det in detectors]

def check_state(ensemble, detectors):
  drift_votes = sum(filter(detectors, lambda x: x.drift_state == "drift"))
  return drift_votes/len(detectors) >= .5

curry_functions= [update, check_state]
my_ensemble = Ensemble(curry_functions, [det1, det2, det3])
#and then Ensemble runs curry_functions at each step, passing the detector list
```

and so if we wanted to have "standard" functions for this purpose, they could look like:
```
pipeline = [ menelaus.curry_fn_for_adwin(user-specifies-args-they-would-normally-specify-in-init), ... ] 
```
which we might be able to get for "free" by defining a decorator for e.g. `update`.

This seems really flexible. It's an unfamiliar setup for me, so I think I'll take some more time to nail down the cases we need to handle for the ensembler and we can check whether this can handle them vs. whether we'll need to write a lot of new repetitive code.

**Comment by Anmol-Srivastava** [comment]
```python
import menelaus.operator as op


ensemble = Ensemble(
	detectors = [
		ADWIN(...),
		KdqTree(...)
	],
	
	pipeline = [
		op.adwin_setup(), # issue <- may need this to return something, and then need to call Adwin.update(),
		op.kdqtree_setup(),

		KdqTree.update,
		Adwin.update,

		op.post()
	]
)

ensemble.run(all_data) 
# may need to pass all batches or all streaming data at once?


for data in data:
	ensemble.update


class Ensemble():
	def __init__(self):
		pass

	def update(self):
		while not self.is_finished:
			# pipe(self, **pipeline)
			pass
```

**Comment by Anmol-Srivastava** [comment]
It looks like it will be better to revert to a non-pipeline idea for ensemble detectors, at least in the batch case. I'll consider this successful if we can get a simple ensemble class running for batch-based data drift detectors:

- [ ] cdbd
- [ ] kdqtree
- [ ] pcacd
- [ ] hdddm
- [ ] histogram density method???
- [ ] optional concept/change detectors too
