### ISSUE TITLE
Have README examples use an ensemble

### ISSUE THREAD

**Issue by Anmol-Srivastava** [mitre/menelaus#99]
### Task

Even an ensemble of two with a single-approval voting scheme would work. Note that ensembles have an IS-A relationship to detectors, so the syntax for the actual ensemble object is the same as in the README examples now. We can decide whether this would be better kept simple (batch ensemble) or demonstrate variety (streaming ensemble)

### Impact

This would immediately draw attention to ensemble capabilities while not losing the instruction of how to operate detector syntax.

**Comment by Anmol-Srivastava** [comment]
@tms-bananaquit this is not an immediate priority, but would you mind closing this issue if you don't agree with putting an ensemble in the REAMDE example?

**Comment by tms-bananaquit** [comment]
Yeah, I think it makes sense to add that. Will not close.

**Comment by tms-bananaquit** [comment]
Also added a note to #94 that we should add some ensemble examples to the notebooks.
